version: '3'

services: 
  api:
    build: ./api
    environment: 
      - HURRIYET_API_KEY=${HURRIYET_API_KEY}
    restart: always
  web:
    build: ./web
    volumes:
      - ./web:/var/www/html
    ports:
      - 8000:80
    depends_on: 
      - api