version: '3'

services: 
  api:
    build: ./api
    environment: 
      - HURRIYET_API_KEY=${HURRIYET_API_KEY}
    restart: always
    ports:
      - 8090:8091
  web:
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    depends_on: 
      - api