version: '3'

services: 
  api:
    build: ./api
    environment: 
      - HURRIYET_API_KEY=${HURRIYET_API_KEY}
    restart: always
    ports:
      - 8000:80
  www:
    build: ./www
    volumes:
      - ./www:/app
    ports:
      - 5000:5000
    depends_on:
      - api